export const AuthErrors = {
  "auth/invalid-email": "Invalid email address",
  "auth/user-disabled": "User disabled",
  "auth/user-not-found": "User not found",
  "auth/wrong-password": "Wrong password",
  "auth/email-already-in-use": "Email already in use",
  "auth/operation-not-allowed": "Operation not allowed",
  "auth/weak-password": "Password is too weak",
  "auth/too-many-requests": "Too many requests",
  "auth/requires-recent-login": "Requires recent login",
  "auth/network-request-failed": "Network request failed",
  "auth/invalid-credential": "Invalid credential",
  "auth/invalid-verification-code": "Invalid verification code",
  "auth/invalid-verification-id": "Invalid verification ID",
  "auth/missing-verification-code": "Missing verification code",
  "auth/missing-verification-id": "Missing verification ID",
  "auth/missing-phone-number": "Missing phone number",
  "auth/missing-continue-uri": "Missing continue URI",
  "auth/missing-iframe-start": "Missing iframe start",
  "auth/missing-ios-bundle-id": "Missing iOS bundle ID",
  "auth/missing-android-pkg-name": "Missing Android package name",
  "auth/missing-app-credential": "Missing app credential",
  "auth/invalid-continue-uri": "Invalid continue URI",
}
